### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by nkvorn** [kangax/html-minifier#690] opened 2016-07-15 20:39 UTC
Hi,

the following code fails to parse properly

``` php
<form class="form-horizontal" role="form" method="POST"
<?php /* action="<?php echo e(route('admin.post.update', $id)); ?>"> */ ?>
action="<?php echo e(Llz::localizeURL("/admin/post/$id")); ?>">
<input type="hidden" name="_token" value="<?php echo e(csrf_token()); ?>">
<input type="hidden" name="_method" value="PUT">
</form>
```

**Comment by alexlamsl** [comment] 2016-07-17 09:24
The default value in `ignoreCustomFragments` won't handle that nested `<?php ?>` you've got in here, so you'll have to adjust the regex yourself.

**Comment by nkvorn** [comment] 2016-07-22 08:49
Hmm, on first look it seems the regex required would be a little monster! For my use case I think I would be better off by preprocessing the html files removing `\*` like comments...

Maybe this could be a future feature of html-minifier. Adding an option to preprocess files with a regex.

**Comment by alexlamsl** [comment] 2016-07-23 06:16
Since the issue is resolved, closing. If you have any ideas to improve on this feature, PR is always welcome :wink:

**Closed as completed by alexlamsl** 2016-07-23 06:16 UTC
