### ISSUE TITLE
 Cannot read property 'replace' of undefined at collapseWhitespace

### ISSUE THREAD

**Issue by ramthakur1991** [kangax/html-minifier#770] opened 2017-01-06 05:21 UTC
Hi ,
I'm using `html-minifier` module in sails(0.11.5) version and getting the following error .
`TypeError: Cannot read property 'replace' of undefined
    at collapseWhitespace (/var/www/apache/edyx_prod_fixes/test/node_modules/html-minifier/src/htmlminifier.js:45:14)
    at minify (/var/www/apache/edyx_prod_fixes/test/node_modules/html-minifier/src/htmlminifier.js:824:13)
    at exports.minify (/var/www/apache/edyx_prod_fixes/test/node_modules/html-minifier/src/htmlminifier.js:1310:10)`

I'm using the following code to minify the ejs template .

`var minify = require('html-minifier').minify;
var ejs = require('ejs-locals');
var parsing = function(path,options,fn) {
    options.locals = options.locals || {};
    options.locals._layoutFile = 'layout.ejs';
    ejs(path, options, function(err, str){
      str = minify(str,{collapseWhitespace: true, removeComments: true});
      return fn(err, str);
    });
};`

`module.exports.views = {
     engine: {
        ext: 'ejs',
        fn: parsing
      },
     layout: false
}`

Waiting for your response 
Thanks

**Comment by alexlamsl** [comment] 2017-01-06 08:10
`str` needs to be a string, which isn't what has been supplied there.

Not a bug with `html-minifier` - closing.

**Closed as completed by alexlamsl** 2017-01-06 08:10 UTC
