### ISSUE TITLE
RegExp is crashing the process

### ISSUE THREAD

**Issue by dciccale** [kangax/html-minifier#349] opened 2015-04-04 11:14 UTC
try the following line of code in the browser or node through terminal (is going to hang the process)
is not crashing firefox though.. 

``` javascript
'<input type="email" name="email" class="form-control" ng-model="user.email" required'.match(/^<([\w:-]+)((?:\s*[\w:.-]+(?:\s*(?:(?:=))\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/)
```

is not actually crashing the process but takes a veeery long time to return and adding more attributes to the html is even worst. Related to #213 

this regexp is returned by `startTagForHandler` and the string is actually part of the html that is going through the parser.

apparently for what I googled, is a bug in the js engine http://stackoverflow.com/questions/12825950/why-does-this-javascript-match-function-crash-my-browser

**Comment by kangax** [comment] 2015-07-03 17:55
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:55 UTC
