### ISSUE TITLE
New autoclosing going against original intent of the HTML

### ISSUE THREAD

**Issue by devinus** [kangax/html-minifier#562] opened 2016-03-17 20:01 UTC
The new "phrasing content model" PR (https://github.com/kangax/html-minifier/pull/541) -- while outputting spec compliant HTML -- is mutating the HTML in a way that is against the original intent.

For example, we have some HTML that has `<div>`s within a `<label>` as a browser hack.

**Comment by alexlamsl** [comment] 2016-03-18 03:00
Duplicate of #565.

**Closed as completed by alexlamsl** 2016-03-18 03:00 UTC
