### ISSUE TITLE
Add support for preserving trailing slash in tags

### ISSUE THREAD

**Issue by bnavetta** [kangax/html-minifier#76] opened 2013-07-05 16:27 UTC
No matter how they are originally formatted, `<link>` tags end up with no slash or closing tag. For example, `<link href="/foo.css"/>` would result in `<link href="/foo.css">`. This even happens with all options disabled. As a result, running minified files through something like [Thymeleaf](http://www.thymeleaf.org) produces an error because they expect valid XML with closed tags.

**Comment by kangax** [comment] 2013-08-20 09:57
This is by design, since the parser was made HTML4-compliant. I'm marking this "possible feature" though.

**Comment by kotnik** [comment] 2014-02-13 16:51
Since we heavily use custom AngularJS directives, we got hit with this as well. If html-minifier supported leaving closing slashes, we'd be able to use singleton tags and have nicer looking HTML.

@kangax would it help if I provide pull request for this, or you are just reluctant to add this option?

**Comment by kangax** [comment] 2014-02-13 16:52
@kotnik if we make it optional, and seeing how it's a commonly-requested option, I don't see why not :) PR is welcome!

**Closed as completed** 2014-02-14 02:04 UTC
Labels: possible-feature
