### ISSUE TITLE
Keeping Trailing Semicolons in Style Attribute

### ISSUE THREAD

**Issue by DChristiany** [kangax/html-minifier#852] opened 2017-10-04 13:05 UTC
Hi,

We're using the html-minifier to minify html emails.
We found out, that removing all trailing semicolons in style attributes destroys our layouts on some email clients.

We would like to add an option (WIP name is allowTrailingSemicolonInStyle) to the html minifier, adapt the behavior, write some text and add an explanation in the README.
Is that okay with you?

Also: Is there something we need to know in order to do this?

Thanks a lot
Daniel

**Comment by alexlamsl** [comment] 2017-10-05 13:59
Closing as duplicate of #798

**Closed as completed by alexlamsl** 2017-10-05 13:59 UTC
