### ISSUE TITLE
removeComments removes `htmlignore` fragments

### ISSUE THREAD

**Issue by XhmikosR** [kangax/html-minifier#696] opened 2016-07-27 12:33 UTC
/CC @alexlamsl 

So with these options https://github.com/mpc-hc/mpc-hc.org/blob/master/Gruntfile.js#L34 and this file https://github.com/mpc-hc/mpc-hc.org/blob/master/source/driver-crash.md the php tags are being removed.

Previously this worked fine. It's like `removeComments` ignores `<!-- htmlmin:ignore -->`.

Using v3.0.1.

**Comment by alexlamsl** [comment] 2016-07-27 21:40
@XhmikosR I've just landed in Osaka.

Let me look at this when I sat down in a hotel later this evening.

**Comment by alexlamsl** [comment] 2016-07-28 17:29
Narrowing down the options, I can reproduce the missing `<?php>` issue with

```
{
  ignoreCustomComments: [/^\s*google(off|on):\s/],
  removeComments: true
}
```

Removing either the bug will not surface. Investigating.

**Comment by alexlamsl** [comment] 2016-07-28 17:51
Oh root cause is actually quite straightforward - default value for `ignoreCustomComments` has `/^!/`, which when overrode trips `<!-- htmlmin:ignore -->` replacements.

I'll sleep on this and come up with a fix. Thanks for spotting this @XhmikosR

**Comment by XhmikosR** [comment] 2016-07-28 17:53
Thanks for looking into it. I noticed it accidentally the other day. Do you
know which version broke it?

**Comment by alexlamsl** [comment] 2016-07-28 18:05
I haven't tested explicited but https://github.com/kangax/html-minifier/commit/b75a4207b56abd8d0f6fda7057e1ff45144d92e0 looks like the culprit, so `2.0.0` would be the last version that works, and `2.1.0` onwards are broken...

**Comment by XhmikosR** [comment] 2016-07-28 18:06
Damn it was broken for so long :/

**Closed as completed** 2016-07-30 07:58 UTC
Labels: bug
