### ISSUE TITLE
Parser hangs on certain HTML input

### ISSUE THREAD

**Issue by richardwillars** [kangax/html-minifier#480] opened 2016-02-03 09:41 UTC
When using this HTML:

`<td cellpadding="0" cellspacing="0" border="0" height="1" ;="" style="line-height: 1px; min-width: 600px;">test</td>`

The minifier completely hangs and renders the node.js app inaccessible.

Note the ;="" in the markup. I know it's not valid HTML, but could it be made to not crash or strip it out?

**Comment by kangax** [comment] 2016-02-03 16:12
Duplicate of #332

**Closed as completed by kangax** 2016-02-03 16:12 UTC
