### ISSUE TITLE
Not minifying when custom HTML tags are present

### ISSUE THREAD

**Issue by Kurtz1993** [kangax/html-minifier#397] opened 2015-08-15 07:32 UTC
I read an .html file with the fs.readSync(file, 'utf8') method, but it seems that it's not minifying the code since I'm seeing the same not-minified HTML in the output.

Here's the code I use:
      var source = fs.readFileSync(file, 'utf8');
      var result = htmlMinifier(source, hookConf.htmlOptions);
      console.log(result);
      fs.writeFileSync(file, result, 'utf8');

Where hookConf.htmlOptions are:
    "htmlOptions":{
        "useShortDoctype": true,
        "keepClosingSlash": true,
        "collapseWhiteSpace": true,
        "removeEmptyAttributes": true,
        "removeAttributeQuotes": true,
        "collapseBooleanAttributes": true,
        "removeScriptTypeAttributes": true,
        "removeStyleLinkTypeAttributes": true
    }

Here's the screenshot where I see the result of minifying and it's still the same unminified HTML file...
![screen shot 2015-08-15 at 2 31 32 am](https://cloud.githubusercontent.com/assets/5412470/9287949/c3bd6b08-42f5-11e5-98ba-b9f519d0e81b.png)

**Comment by Kurtz1993** [comment] 2015-08-25 21:32
Apparently this issue only occurs when custom HTML tags are present... any plans for adding custom HTML tags support?

**Comment by kangax** [comment] 2015-10-03 03:10
Duplicate of https://github.com/kangax/html-minifier/issues/382

**Closed as completed by kangax** 2015-10-03 03:10 UTC
