### ISSUE TITLE
Problem when minifying <script> tags

### ISSUE THREAD

**Issue by crafter999** [kangax/html-minifier#882] opened 2018-01-31 15:18 UTC
Hi, I have the following code running on Node.js 9.3.0 with html-minifier version 3.5.8 but it's not minifying **javascript** blocks properly. Is there anything wrong with my code or something? If so, could you be more specific about minifyjs on your docs about this feature? Thanks
## CODE
```
const minify = require("html-minifier").minify;
const fs = require("fs");

let html = `
   <html>
   <body>
   <div id="content"></div>
   <script>
        // im a comment
        let hello = "hello";
        let world = "world";
        document.getElementById("content").innerText=hello+" "+world;
   </script>
   </body>
   </html>
`;

let minifiedHtml = minify(html, {
   removeComments: true,
   minifyJS: true,
   collapseWhitespace: true
});

fs.writeFileSync("test.html",minifiedHtml);
```
## RESULT

```
<html><body><div id="content"></div><script>// im a comment
        let hello = "hello";
        let world = "world";
        document.getElementById("content").innerText=hello+" "+world;</script></body></html>
```

**Comment by alexlamsl** [comment] 2018-01-31 15:45
Closing as duplicate of #877 - `uglify-js` supports JavaScript only, while your input is ES6.

**Closed as completed by alexlamsl** 2018-01-31 15:45 UTC
