### ISSUE TITLE
Typo blocking html-minifier completely

### ISSUE THREAD

**Issue by SnapLyte** [kangax/html-minifier#342] opened 2015-03-30 03:59 UTC
Hey,
I just had a major issue with html-minifier after someone wrote `"=""` in an img object.
It completely froze html-minifier and kept using 100% of cpu (infinite loop maybe).

Here is an example of the issue:

```
<html>
<body>
<table>
    <tr>
        <td>
            <img src="http://my.website.com/image/fullsize/5fe6f5a28eff88007dc581abbfd82042cf0fd4e4.jpg" "="" style="display:block" border="0" width="600" height="100" alt="">
        </td>
    </tr>
</table>
</body>
</html>
```

I do get an error message if the image file name is short (~20 characters) but it freezes completely when I use a longer file name. Not sure how this is related...

Please, could you add an exception if the script gets stuck or if the html code has invalid attributes?
Thanks!

**Comment by ashclarke** [comment] 2015-04-02 17:43
In my case, I had an extra quote at the end of an opening tag:

```
<div attr="x"
    attr="y"
    attr="z" "></div>
```

Took me an hour to figure out what was happening D:

Thanks for raising this issue @seb-angel as I'd probably still be figuring it out.

**Comment by tssajo** [comment] 2015-04-05 21:36
These are more than likely related to https://github.com/kangax/html-minifier/issues/213

**Comment by fregante** [comment] 2015-07-01 10:48
Invalid HTML is not supported. Duplicate of #375 (or vice versa)

**Comment by kangax** [comment] 2015-07-03 17:55
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:55 UTC
