### ISSUE TITLE
IE conditional comment "bubbling" does not get minified correctly

### ISSUE THREAD

**Issue by kristerkari** [kangax/html-minifier#157] opened 2014-04-15 22:17 UTC
[This markup](http://nicolasgallagher.com/better-conditional-classnames-for-hack-free-css/#the-bubble-up-conditional-comments-method):

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
    <!--[if IE 7]><html class="no-js ie7"><![endif]-->
    <!--[if IE 8]><html class="no-js ie8"><![endif]-->
    <!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->

    <title>Document</title>
  </head>
  <body>
  </body>
</html>
```

With "safe" options gets minified to:

``` html
<!DOCTYPE html>
<html lang=en>
<head>
<meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
<meta charset=utf-8>
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class=no-js><!--<![endif]-->
<title>Document</title>
</html>
</head>
<body>
</body>
</html>
```

there is one extra closing `</html>` before `</head>`.

**Comment by kristerkari** [comment] 2014-04-15 22:27
This works:

``` html
<!--[if IE]><![endif]-->
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <title>Document</title>
  </head>
  <body>
  </body>
</html>
```

Minified:

``` html
<!--[if IE]><![endif]-->
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class=no-js><!--<![endif]-->
<head>
<meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
<meta charset=utf-8>
<title>Document</title>
</head>
<body>
</body>
</html>
```

**Comment by kristerkari** [comment] 2014-04-15 22:32
``` html
<!DOCTYPE html>
<html lang="en">
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <title>Document</title>
  </head>
  <body>
  </body>
</html>
```

Minified:

``` html
<!DOCTYPE html>
<html lang=en>
<!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
<!--[if IE 7]><html class="no-js ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie8"><![endif]-->
<!--[if gt IE 8]><!--><html class=no-js><!--<![endif]-->
<head>
<meta charset=utf-8>
<title>Document</title>
</head>
<body>
</body>
</html>
</html>
```

Two `</html>` tags.

**Comment by kangax** [comment] 2014-04-16 00:35
I can't reproduce this on http://kangax.github.io/html-minifier/

**Comment by kristerkari** [comment] 2014-04-16 05:51
Uncheck "remove optional tags".

**Comment by kangax** [comment] 2014-04-16 16:09
Got it. Ok, will look into it.

**Comment by alexlamsl** [comment] 2016-02-05 07:52
AFAICT the failing cases are all invalid HTML - whichever conditional comment gets evaluated to true the end result would be two &lt;html&gt;'s with only one &lt;/html&gt;

Your working case is how I'd expect to function.

**Comment by alexlamsl** [comment] 2016-02-20 15:15
Given that even [W3C Validator](https://validator.w3.org/) isn't happy with your example ("Stray start tag `html`"), I don't think we can do much about that.

**Comment by kristerkari** [comment] 2016-02-21 14:29
Yeah, I think that W3C Validator does not like most of the things (hacks) that actually fix problems in real browsers, and that's why nobody has been using W3C validator in the last 10 years.

**Comment by alexlamsl** [comment] 2016-02-21 15:59
Fair point - though I've checked in real browsers (IE11 and Chrome), and both seems to be equally happy with your example which works with `html-minifier`

Is there a reference to using `<html>` within `<head>` anywhere which I can read up on about?

**Comment by kristerkari** [comment] 2016-02-21 16:27
I'm not sure where to find info about having `<html>` inside `<head>`, but if you want you can have a look at this post, which has many links related to the hack:
http://nicolasgallagher.com/better-conditional-classnames-for-hack-free-css/#the-bubble-up-conditional-comments-method

and this post also has some pros and cons listed:
https://mathiasbynens.be/notes/safe-css-hacks#conditional-classnames

**Comment by alexlamsl** [comment] 2016-02-21 16:46
Given [this section](https://github.com/kangax/html-minifier#working-with-invalid-markup) in `README.MD`, I think our hands are a bit tied :sweat:

And within the same article, the [preemptive method](http://nicolasgallagher.com/better-conditional-classnames-for-hack-free-css/#the-preemptive-conditional-comments-method) seems to achieve the same goals and is valid HTML:

```
> minify(`
  <!--[if IE]><![endif]-->
  <!DOCTYPE html>
  <!--[if lt IE 7]><html class="no-js ie6"><![endif]-->
  <!--[if IE 7]><html class="no-js ie7"><![endif]-->
  <!--[if IE 8]><html class="no-js ie8"><![endif]-->
  <!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta charset="utf-8">
      <title>Document</title>
    </head>
    <body>
    </body>
  </html>
  `, {
    collapseWhitespace: true,
    removeOptionalTags: true
  });

'<!--[if IE]><![endif]--><!DOCTYPE html><!--[if lt IE 7]><html class="no-js ie6"><![endif]--><!--[if IE 7]><html class="no-js ie7"><![endif]--><!--[if IE 8]><html class="no-js ie8"><![endif]--> <!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]--><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta charset="utf-8"><title>Document</title>'
```

**Comment by kristerkari** [comment] 2016-02-21 17:52
I guess it does not make much sense to try to fix it if tree parsing can handle it. I originally reported this because the most known conditional comment bubbling hack was not getting minfied correctly. Thanks for taking a look at it!

**Comment by alexlamsl** [comment] 2016-02-22 07:08
@kristerkari just to confirm my understanding of this hack - is the only case of this being `<html>` inside of `<head>` and nothing else in the wild?

If so, I may have an idea on fixing this... :smiling_imp:

**Comment by kristerkari** [comment] 2016-02-22 10:21
Yes, the first example that I posted is the one broken from the blog post. The third one that I posted is probably just me trying to find a different way to break the minifier. I haven't heard of other hacks for this, and I don't develop things for old IE any longer. :)

**Comment by alexlamsl** [comment] 2016-02-22 10:32
Amazon and Ebay seem to be happily using the HTTP response header to handle `X-UA-Compatible`, but then I guess there will be instances, e.g. free web hosts, which people will resort to this hack.

Would love to figure out some actual sites using this hack. Having said that, the "fix" I have in mind is an one-liner to `htmlparser.js`, assuming I got it right :sweat_smile:

**Comment by kristerkari** [comment] 2016-02-22 11:08
> Amazon and Ebay seem to be happily using the HTTP response header to handle X-UA-Compatible, but then I guess there will be instances, e.g. free web hosts, which people will resort to this hack.

This hack has nothing to do with `X-UA-Compatible` meta tag or header. The hack can be used to get correct class names in `<html>` tag for IE6-8, e.g. `<html class="no-js ie8">`.

You are able to the use those classnames to scope things for old IE in your CSS, e.g. `.ie8 .my-class {}`

**Comment by alexlamsl** [comment] 2016-02-22 11:13
From the article you referenced, this hack is solving additional problems on top of conditional stylesheets:

> The Compatibility View icon is displayed in IE8 and IE9 if you are not setting the X-UA-Compatible header in a server config.

And later:

> The conditional classes are then assigned in a second html tag that appears after the &lt;meta http-equiv="X-UA-Compatible"&gt; tag in the document.

**Comment by kristerkari** [comment] 2016-02-22 11:21
Oh yeah true. I think that the `X-UA-Compatible` meta tag is good to have there as a fallback even if you are sending it as a header.

**Closed as completed** 2016-03-02 20:56 UTC
Labels: bug
