### ISSUE TITLE
minifier hangs on parsing errors caused by angular brace mismatch

### ISSUE THREAD

**Issue by jrencz** [kangax/html-minifier#177] opened 2014-05-26 07:48 UTC
After parsing tags with missing right angular brace like this:

``` html
<foo bar="1" baz</foo>
```

Parse error is thrown but parsing time is not always the same. For some attributes (especially attributes with dashes and used with without the value what is common when  angular attribute directives are used) parser tends to hang for several seconds and even several minutes sometime.

I use html-minifier via the [ngtemplates](https://github.com/ericclemmons/grunt-angular-templates) grunt plugin. I already discussed the problem with @ericclemmons and we both think the problem is closer to the minifier itself than the grunt plugin.

Cold you please take a look at https://github.com/ericclemmons/grunt-angular-templates/issues/91 where I described the problem and minifier settings in detail?

**Comment by kangax** [comment] 2014-06-01 14:06
I'll mark this as "possible feature" in a sense that we might consider optimizing parser to report these errors sooner. I have a feeling this could be caused by catastrophic backtracking and is common when giving certain input to certain parsers. If anyone has time to look into it, I'll gladly consider merging this in.

**Comment by alexlamsl** [comment] 2016-03-03 04:51
I think this is fixed by #510 - please reopen if that's not the case.

**Closed as completed by alexlamsl** 2016-03-03 04:51 UTC
Labels: possible-feature
