### ISSUE TITLE
This file makes minifer hang forever with 100% processor

### ISSUE THREAD

**Issue by snowindy** [kangax/html-minifier#375] opened 2015-06-08 08:44 UTC
I found this issue when used another plugin https://github.com/tolyo/html-pages-brunch/issues/1#issuecomment-109786039

Version of plugin is 0.7.2

$ node -v
v0.12.4

```
<div class="widget-title pm-modal-header"><span class="icon"> <i class="icon-align-justify"></i></span>
    <h5 ng-i18next="app.logged-in.template.raw-template-code"></h5>
</div>

<div class="modal-body pm-modal-full-screen-body pm-boxed-content" style="padding: 40px 0px 60px 0px;>
    <div class="pm-boxed-content-relative">     
        <div class="spinner-large-white" ng-show="loadingTemplate == true"></div>   
        <textarea id="templateCode" pm-code-editor mode="template.mode" content="template.content" width="100%" height="100%"></textarea>
    </div>
</div>
<div class="modal-footer pm-wizard-form-actions">
    <button class="btn btn-primary" ng-click="ok()"><i class="icon-ok icon-white pm-button-icon"></i>OK</button>
</div>

```

**Comment by duncanbeevers** [comment] 2015-06-08 15:28
This is broken HTML. You can see one of the style tags is unclosed. html-minifier doesn't do well with simply broken markup.

**Comment by snowindy** [comment] 2015-06-08 15:30
At least it should complain somehow and quit instead of hanging process without a single message.

**Comment by snowindy** [comment] 2015-06-08 15:32
If you don't like adding pre-validation code you could allow thing to count milliseconds since start of processing of portion of html.
If for example it takes more than, say, 10s - it's definitely a html markup bug - you may report it.

**Comment by hwoarangzk** [comment] 2015-07-03 12:38
I ran into the similar problem. At least I expect html-minfier to throw an error when there is a broken html so that I can catch it. Is there any further updates of html-minifier to solve this issue?

**Comment by kangax** [comment] 2015-07-03 17:55
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:55 UTC
