### ISSUE TITLE
When a non html character is present in the wrong place, html-minifier will hang with no error reported.

### ISSUE THREAD

**Issue by tagama** [kangax/html-minifier#333] opened 2015-01-27 18:08 UTC
``` html
<input class="form-control" type="text" ng-model="entity.nisi" ng-required="true" placeholder="Nisi"  } id="nisi" />
```

**Comment by kangax** [comment] 2015-01-27 22:12
Duplicate of #306, etc.

**Closed as completed by kangax** 2015-01-27 22:12 UTC
