### ISSUE TITLE
minifier hangs on broken html

### ISSUE THREAD

**Issue by zfedoran** [kangax/html-minifier#379] opened 2015-06-18 19:45 UTC
This could potentially be related to another open issue but opening a new one just in case it is not.

My attempts at simplifying the problem yielded working examples. In the following screenshot, only the last hangs but the execution time does increase with each line.

![image](https://cloud.githubusercontent.com/assets/623790/8240453/b59c79d0-15d0-11e5-8a50-28be2747c32f.png)

It looks like there is something special about the following string that causes the minifier to hang:

```
var minify = require('html-minifier').minify;
minify('<input class="set-notification-type__option" type="radio" name="notification" value="1" id="{{ name }}__notificationErr"')
```

**Comment by fregante** [comment] 2015-07-01 10:29
While it probably shouldn't hang like that, the docs say that

> [HTMLMinifier can't work with invalid or partial chunks of markup](https://github.com/kangax/html-minifier#working-with-invalid-markup)

Also, looks like a duplicate of #375

**Comment by kangax** [comment] 2015-07-03 17:55
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:55 UTC
