### ISSUE TITLE
Space between two <button> tags causes a bug

### ISSUE THREAD

**Issue by DmitryGonchar** [kangax/html-minifier#283] opened 2014-10-13 16:53 UTC
Hi! First of all, thank you for the tool! Secondly, about the bug: 
If you insert this into http://kangax.github.io/html-minifier/ 
1) 

```
<div>
  <button>Abc</button>
  <button>123</button>
</div>
```

the result will be:
2) 
`<div><button>Abc</button> <button>123</button></div>`
html-minifier plugin result is the same.

Now, if somebody adds some styles to it [**like in this plunk**](http://plnkr.co/edit/OHinxCPd2zhWYbUcE7Hi?p=preview) - then there will be a bug (offset between buttons), which was not present in 1) but is present in 2). Also, if you remove space between two button tags - it will look ok again.

The question is - why do you add a space between two <button> tags? Is it required? Can this issue be fixed?

I also assume that this issue is more general and broad.

**Comment by kangax** [comment] 2014-10-16 15:45
Duplicate of #273

**Closed as completed by kangax** 2014-10-16 15:45 UTC
