### ISSUE TITLE
End tag is being removed and I have no option to keep it

### ISSUE THREAD

**Issue by kirkstrobeck** [kangax/html-minifier#97] opened 2013-11-26 19:23 UTC
Before minifying

```
Validation started for.. digest-notification/dist/index.html
>> Validation successful..
Validation report generated: validation-report.json
```

After minifying

```
Validation started for.. digest-notification/dist/index.html
1=> "end tag for \"meta\" omitted, but OMITTAG NO was specified" Line no: 1
2=> "start tag was here" Line no: 1
3=> "end tag for \"meta\" omitted, but OMITTAG NO was specified" Line no: 1
4=> "start tag was here" Line no: 1
5=> "end tag for \"img\" omitted, but OMITTAG NO was specified" Line no: 1
6=> "start tag was here" Line no: 1
7=> "end tag for \"br\" omitted, but OMITTAG NO was specified" Line no: 1
8=> "start tag was here" Line no: 1
9=> "end tag for \"br\" omitted, but OMITTAG NO was specified" Line no: 1
10=> "start tag was here" Line no: 1
11=> "end tag for \"img\" omitted, but OMITTAG NO was specified" Line no: 1
12=> "start tag was here" Line no: 1
No of errors: 12
Validation report generated: validation-report.json
```

It is removing the trailing slash on tags like `meta`

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!-- to -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

I want to **keep** the trailing slash ..

I am using `XHTML 1.0 Transitional` which requires said slashes.

**Comment by kangax** [comment] 2014-02-03 20:39
Duplicate of #76

**Closed as completed by kangax** 2014-02-03 20:39 UTC
Labels: possible-feature
