### ISSUE TITLE
Make SVG tag special so that trailing links are not stripped inside

### ISSUE THREAD

**Issue by AlexMeah** [kangax/html-minifier#78] opened 2013-08-14 15:29 UTC
The script strips the closing tags of inline SVG elements

```
<path fill="#A6D383" d="M493.1 622.399L428.5"/>
```

becomes

```
<path fill="#A6D383" d="M493.1 622.399L428.5">
```

Easily fixed by added SVG to

```
// Special Elements (can contain anything)
var special = makeMap("script,style");

// Special Elements (can contain anything)
var special = makeMap("script,style,svg");
```

**Comment by kangax** [comment] 2013-08-20 10:00
This is somewhat related to https://github.com/kangax/html-minifier/issues/76

**Comment by albell** [comment] 2014-01-27 18:59
+1. Perhaps break out removing svg closing tags as an option?

**Comment by kangax** [comment] 2014-02-03 20:39
Duplicate of #76

**Closed as completed by kangax** 2014-02-03 20:39 UTC
Labels: possible-feature
