### ISSUE TITLE
endless loop/freeze case

### ISSUE THREAD

**Issue by kelson42** [kangax/html-minifier#351] opened 2015-04-05 17:15 UTC
This url
http://rest.wikimedia.org/eo.wikipedia.org/v1/page/html/Ciklada_kulturo/5636524

With this:
htmlMinifier.minify( html, {
                removeComments: true,
                conservativeCollapse: true,
        collapseBooleanAttributes: true,
                removeRedundantAttributes: true,
                removeEmptyAttributes: true,
        minifyCSS: true );

**Comment by tssajo** [comment] 2015-04-05 21:37
This is possibly related to https://github.com/kangax/html-minifier/issues/213

**Comment by kangax** [comment] 2015-07-03 17:54
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:54 UTC
