### ISSUE TITLE
First line in tag p end with single line close tag p is transted into [{htmlmin-lb}]

### ISSUE THREAD

**Issue by rexdf** [kangax/html-minifier#316] opened 2014-12-23 10:16 UTC
``` js
dist: { // Target
        options: { // Target options
            preserveLineBreaks: true,
            collapseWhitespace: true,
        },
        files: { // Dictionary of files
            'public2/index.html': 'public/index.html', // 'destination': 'source'
        }
    }
```

public/index.html

``` html
<p>
anything
</p>
```

public2/index.html

``` html
<p>
anything[{htmlmin-lb}]</p>
```

If a line end with `-`  it will be coverter to -[{htmlmin-lb}].

**Comment by kangax** [comment] 2014-12-23 12:52
Works for me:

``` sh
> html-minifier -v
html-minifier v0.6.9
> echo "<p>x</p> <p>y</p>" | html-minifier --collapse-whitespace --preserve-line-breaks
```

Must be something with config of whatever you're wrapping htmlminifier with

**Comment by rexdf** [comment] 2014-12-24 02:12
@kangax  You can try `echo -e "<p>\na\n</p>" | html-minifier --collapse-whitespace --preserve-line-breaks`.

**Comment by kangax** [comment] 2014-12-25 11:14
Thanks, reproduced! Marking as bug.

**Comment by danielwg** [comment] 2015-01-29 11:42
This bug appeared to be fixed by 2a57787ea5b0310c41e992dd7b073f3fe5c0f145

**Comment by kangax** [comment] 2015-01-29 11:47
ok, thanks

**Closed as completed by kangax** 2015-01-29 11:47 UTC
Labels: bug

**Comment by rainboxx** [comment] 2015-02-01 23:25
Waiting for this fix to appear in a release. Is there already a schedule for releasing v0.6.10?

**Comment by kangax** [comment] 2015-02-04 12:27
@rainboxx just pushed 0.7!

**Comment by rainboxx** [comment] 2015-02-04 14:56
Awesome, thanks!
