### ISSUE TITLE
collapseWhitespace removes <!doctype>

### ISSUE THREAD

**Issue by brunoDegaspare** [kangax/html-minifier#725] opened 2016-09-26 16:12 UTC
After minifying using `collapseWhitespace: true` it always removes <!DOCTYPE html> from top of html. Is there a fix for that issue?

**Comment by alexlamsl** [comment] 2016-09-26 16:21
I just tried it [here](https://kangax.github.io/html-minifier/)

```
<!doctype html>
<html>
<body>
<h1>Hello World!</h1>
</body>
</html>
```

gives me:

```
<!DOCTYPE html><h1>Hello World!</h1>
```

Would you mind giving me an example of the problem you've described?

**Comment by alexlamsl** [comment] 2016-09-26 16:22
... the same example but with `collapseWhitespace` only:

```
<!DOCTYPE html><html><body><h1>Hello World!</h1></body></html>
```

**Comment by brunoDegaspare** [comment] 2016-09-26 16:41
Hi @alexlamsl,

Yeah, this is what I am using:

```
htmlmin: {
   index: {
     options: {
         removeComments: false,
         collapseWhitespace: true
     },
     files: {
         'prod/index.html': 'dev/index.html'
      }
   }
}
```

Not sure what I am missing here.

This is the output that I get:

```
<script src="assets/js/app.min.js"></script>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--></head><body> (content here) </body></html>
```

**Comment by alexlamsl** [comment] 2016-09-26 17:12
1. that doesn't look like a direct use of `html-minifier`
   - which module are you using?
   - do they use the latest version of `html-minifier`?
2. you have only provided the minified output - what does the input looks like?
3. I notice the use of IE's conditional comment there, so may be that's related.

**Comment by alexlamsl** [comment] 2016-09-29 05:00
Closing for now. Will reopen if a reproducible case is provided.

**Closed as completed by alexlamsl** 2016-09-29 05:00 UTC
