### ISSUE TITLE
Optionally minify whitespace inside of <script> tags?

### ISSUE THREAD

**Issue by PunkChameleon** [kangax/html-minifier#88] opened 2013-10-04 14:02 UTC
Hey all,

Great plugin. However, I'm using this for a web application that has a ton of mustache templates in script tags -- which are not being minified in the collapse Whitespace rule.

Is there an optional parameter to make this happen? The reason I ask is that my benchmarks get much lower if I minify all of the whitespace (using http://www.willpeavy.com/minifier/, or something of the sort). Here are my marks:

Normal : 31.7kb
grunt-contrib-html (with all options set to true): 29.2 kb
white space minification: 21.6 kb

I would love to utilize the rest of the tools in this as well, but the whitespace in script tag blocker is holding my back by around 8 kbs. Is it possible to turn that off?

**Comment by iameli** [comment] 2013-10-26 00:51
+1. I think this could be done easily enough, I may try my hand if I find the time. I'm using this via grunt-htmlmin to compile an Angular project, and the bits of my markup in `<script type="text/ng-template">` tags don't get compressed. 

Could be as easy as adding an option that's a list of script types not to minify.

**Comment by PunkChameleon** [comment] 2013-10-26 03:33
+1 - that sounds fantastic. It can default to not minify anything if none are listed, so it'd only effect those who would want or need it

**Comment by kangax** [comment] 2014-02-03 20:42
Duplicate of #56

**Closed as completed by kangax** 2014-02-03 20:42 UTC
