### ISSUE TITLE
Error: Parse Error: <<上一章

### ISSUE THREAD

**Issue by bluelovers** [kangax/html-minifier#897] opened 2018-03-25 05:17 UTC
version html-minifier@3.5.11

parse fail when html has bad `<<`

```html
<ul class="">
                                                <li><a class="" href="/index.php">首页</a></li>
                        <li><a href="/0/103/0.html"><<上一章</a></li>
                        <li><a href="/0/103/">返回目录</a></li>
                        <li><a href="http://www.webqxs.com/modules/article/addbookcase.php?bid=103&cid=14751" target="_Blank">加入书签</a></li>
                        <li><a href="http://www.webqxs.com/modules/article/bookcase.php" target="_Blank">我的书架</a></li>
                        <li><a href="/0/103/14752.html">下一章>></a></li>
                    </ul>
```

**Comment by alexlamsl** [comment] 2018-03-25 05:48
Duplicate of #863

**Closed as completed by alexlamsl** 2018-03-25 05:48 UTC

**Comment by bluelovers** [comment] 2018-03-25 06:17
also this
```html
<a class="u-index-rigster" href="javascript:zh_tran('s');" class="zh_click" id="zh_click_s"">简体</a>
```
