### ISSUE TITLE
Empty string attribute value inside single quotes throws a TypeError

### ISSUE THREAD

**Issue by albell** [kangax/html-minifier#151] opened 2014-03-28 00:42 UTC
```
<!DOCTYPE html>
<html>
<head>
        <meta name="description" content=''>
</head>
<body>
</body>
</html>
```

<a href="http://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2">The spec</a> allows single quotes for attribute values, including empty string values.

**Comment by kangax** [comment] 2014-04-01 21:41
Duplicate of #150

**Closed as completed by kangax** 2014-04-01 21:41 UTC
