### ISSUE TITLE
Can we use dependency uglify-es instead of uglify-js

### ISSUE THREAD

**Issue by sahaam** [kangax/html-minifier#890] opened 2018-03-08 21:29 UTC
Hi,

According to the guild of UglifyJS2
uglify-js only supports ECMAScript 5 (ES5).
Those wishing to minify ES2015+ (ES6+) should use the npm package uglify-es.

Can we move to uglify-es?

**Comment by alexlamsl** [comment] 2018-03-09 02:14
Duplicate of #843

Contains a solution on how to use custom proccessor in `minifyJS`.

**Closed as completed by alexlamsl** 2018-03-09 02:14 UTC
