### ISSUE TITLE
Javascript / CSS minification support

### ISSUE THREAD

**Issue by outaTiME** [kangax/html-minifier#56] opened 2013-05-06 20:50 UTC
Hi pal ... it will great to minify javascript / css too ...

like: 

http://www.willpeavy.com/minifier/

from: 

``` html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.1//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es" dir="ltr">
  <head>
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1; minimum-scale=1; user-scalable=0;">
    <title>Login</title>
    <link rel="shortcut icon" href="/assets/images/favicon.ico?_swc=1367872762551" type="image/vnd.microsoft.icon">
    <link rel="icon" type="image/png" href="/assets/images/favicon.png?_swc=1367872762551">
    <link rel="stylesheet" href="/build/css/mobile.css?_swc=1367872762551" type="text/css" media="screen">
  </head>
  <body>
    <div id="content">
      <div id="container">
        <div id="header">
          <div class="logo" id="logo_ct"><img border="0" src="/assets/images/header_small.png?_swc=1367872762551"></div>
          <div class="title">
            <p>Login</p>
          </div>
        </div>
        <div id="main">
          <div id="error_ct" class="error" style="display: none;">La combinaci&oacute;n de usuario y clave es incorrecta.</div>
          <form id="form" action="/" method="post">
            <div class="label">Usuario</div>
            <input type="text" name="username" class="field">
            <div class="label">Clave</div>
            <input class="field" type="password" name="password" autocomplete="off">
            <input type="submit" value="Ingresar" class="button">
          </form>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="build/mobile.js?_swc=1367872762551"></script>
    <script type="text/javascript" src="build/mobile.modules.js?_swc=1367872762551"></script>

<script type="text/javascript">
  <!--
    Platform.Mobile.Bootstrap.init(function () {
      Platform.Mobile.Core.Navigation.go("Login", {
        "error": ""
      });
    });
  //-->
</script>

  </body>
</html>
```

to: 

``` html
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.1//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile11.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es" dir="ltr"><head><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="-1"><meta name="viewport" content="width=device-width;initial-scale=1.0;maximum-scale=1;minimum-scale=1;user-scalable=0;"><title>Login</title><link rel="shortcut icon" href="/assets/images/favicon.ico?_swc=1367872762551" type="image/vnd.microsoft.icon"><link rel="icon" type="image/png" href="/assets/images/favicon.png?_swc=1367872762551"><link rel="stylesheet" href="/build/css/mobile.css?_swc=1367872762551" type="text/css" media="screen"></head><body><div id="content"><div id="container"><div id="header"><div class="logo" id="logo_ct"><img border="0" src="/assets/images/header_small.png?_swc=1367872762551"></div><div class="title"><p>Login</p></div></div><div id="main"><div id="error_ct" class="error" style="display: none;">La combinación de usuario y clave es incorrecta.</div><form id="form" action="/" method="post"><div class="label">Usuario</div><input type="text" name="username" class="field"><div class="label">Clave</div><input class="field" type="password" name="password" autocomplete="off"><input type="submit" value="Ingresar" class="button"></form></div></div></div><script type="text/javascript" src="build/mobile.js?_swc=1367872762551"></script><script type="text/javascript" src="build/mobile.modules.js?_swc=1367872762551"></script><script type="text/javascript"><!-- Platform.Mobile.Bootstrap.init(function (){Platform.Mobile.Core.Navigation.go("Login",{"error": ""});});//--></script></body></html>
```

**Comment by sparanoid** [comment] 2013-08-09 02:55
+1 for CSS minify, one of my projects uses some dynamic style so I have to code `<style>` in HTML templates.

**Comment by iameli** [comment] 2014-02-03 21:02
#88 was closed as a duplicate of this–I think that's probably correct, I just wanted to note here that one of the behaviors that you should be able to specify for the interior of <script> and <style> tags is to pipe the content through the minifier itself.

**Comment by fxck** [comment] 2014-03-13 14:08
Could really, really use this https://github.com/kangax/html-minifier/issues/88#issuecomment-27135804

have you @iameli managed to put something together?

**Comment by iameli** [comment] 2014-03-13 22:17
nuh-uh. We actually stopped using Angular templates defined within other Angular templates so I don't need this feature anymore. Still would be a nice thing, plenty of common frameworks use HTML within `<script>` tags... ICH comes to mind. 

EDIT: Let's formally define the feature request; I appear to have ended my previous comment in the middle of a sentence. It would be nice to be able to specify custom processors for the contents of certain tags. If I hit a `<style>` tag, I want to pipe the contents through a CSS minifier. If I hit a `<script>`, a JS minifier. If I hit a `<script type="text/html">`, I want to process the contents with html-minifier itself.

This feels to me like a mapping of regexes to processor functions. If a tag matches a regex, pipe its contents through a processor before doing anything. Perhaps a `processors` option? Something like...

```
processors = [{
    match: /script/,
    processor: function(contents) {
        return doSomething(contents)
    }
}]
```

I don't anticipate having the time to implement this in the near future but it'd be a sweet thing to have.

**Comment by fxck** [comment] 2014-03-14 08:49
Since this is hmltminifier, I wouldn't care about css or js, but it's imho valid request to be able to minify certain script tags. Something like this would have probably worked..

```
processScripts: ["text/x-handlebars-template", "text/ng-template"]
```

where you'd in an array(or maybe just a string would be enough) define which script types to process.

**Comment by kangax** [comment] 2014-03-17 00:49
I took a first stab at this and added support via `minifyJS` option (uses UglifyJS underneath) — https://github.com/kangax/html-minifier/commit/b1edfe3af74f9d9a1a8d35cdc75d8a9297d8a4b6

Check it out and let me know how it's working.

**Comment by unbug** [comment] 2014-03-17 02:57
+1 @fxck

**Comment by iameli** [comment] 2014-03-17 08:45
Cool!

**Comment by fxck** [comment] 2014-03-17 09:21
Then again @kangax this is why I think the other issue #88 shouldn't have been closed as a duplicate of this one. Because this one wants to actually minify actual inline javascript(using uglify or whatever) and the other wants to use html minification on html templates inside inline javascripts.

**Comment by kangax** [comment] 2014-03-17 21:46
@fxck Wait, html templates inside inline javascripts? What does that look like? Note that currently _all_ script elements' contents are minified:

```
<script type="text/ng-template">var foo = 1; var bar = 2</script>
```

becomes:

```
<script type=text/ng-template>var foo=1,bar=2;</script>
```

**Comment by kangax** [comment] 2014-03-17 21:48
As for CSS minification, what's the best tool (with Node support) to use at the moment?

/cc @XhmikosR @mhulse

**Comment by iameli** [comment] 2014-03-17 23:07
@kangax "Inline Javascripts" wouldn't be the right term. We're talking script tags defining an inline HTML template, like Handlebars and angular have:

```
<script type="text/ng-template">
    <button ng-click="someAngularFunction()">I am a button!</button>
    <!-- More HTML stuff here. -->
</script>
```

Throwing that at a JS minifier is going to be... problematic.

**Comment by mhulse** [comment] 2014-03-17 23:26
@iameli Thanks for posting an example. Interesting. I can see how that could get tricky.

@kangax Lately, I've been using SASS to compress my CSS output ... The last time I used something other than SCSS was [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin) which hooks into [clean-css](https://github.com/GoalSmashers/clean-css):

> ## What is clean-css?
> 
> Clean-css is a fast and efficient [Node.js](http://nodejs.org/) library for minifying CSS files.
> 
> According to [tests](http://goalsmashers.github.io/css-minification-benchmark/) it is one of the best available.

**Comment by kangax** [comment] 2014-03-18 01:41
@mhulse Hmm... I ended up using [CSSO](https://github.com/css/csso) before I saw your comment. I've heard about it before and it's from BEM folks (also creators of SVGO which is quite excellent) so I trust it to be good. We can always switch to another engine in the future.

On this note, I'm closing this ticket now that we have both `minifyCSS` and `minifyJS` options.

**Closed as completed by kangax** 2014-03-18 01:41 UTC
Labels: possible-feature

**Comment by XhmikosR** [comment] 2014-03-18 04:37
https://github.com/kangax/html-minifier/commit/2a5ce0537f2bc4012d2cee06c77763ee3cbd913b#commitcomment-5707076

http://goalsmashers.github.io/css-minification-benchmark/

**Comment by kangax** [comment] 2014-03-18 05:29
@XhmikosR ahha, I was looking for something like that. Thanks! It's good to see that CSSO is pretty much the next best thing after clean-css. Although frankly I can't see much difference between two. They seem to go more or less head-to-head, and clean-css wins by 1 test (and most of the difference is by few bytes). Any other reason for switch? One thing I didn't like about CSSO is that it creates few globals (at least in a browser build).

**Comment by XhmikosR** [comment] 2014-03-18 05:33
The reason I suggest clean-css and that I personally use that, is that it's much better maintained, and less error prone. Especially if you skip advanced optimizations, you should be on the safe side. Less.js is using clean-css too.

The fact that it generates better compression for some tests see https://github.com/GoalSmashers/clean-css/issues?state=open. I've personally suggested many improvements all these years; basically the transforms is why CSSO beats clean-css and I expect that to be sorted soon :/

I opened a ticket for a standalone web version https://github.com/GoalSmashers/clean-css/issues/260 Maybe you could help make that happen sooner and use that here too :)

**Comment by kangax** [comment] 2014-03-18 05:38
@XhmikosR I see... Well, I don't have much time at all right now to help with GoalSmashers/clean-css#260 :) but I'm open to switching to clean-css whenever browser build is ready!

**Comment by XhmikosR** [comment] 2014-03-18 05:56
@kangax: I tried node-browserify and created successfully a standalone file. Can you try this standalone clean-css build?

https://gist.github.com/XhmikosR/fe6db493bc06eb582101

https://github.com/XhmikosR/clean-css/compare/browserify

**Comment by kangax** [comment] 2014-03-18 06:32
Alright, I'll try tomorrow.

**Comment by fxck** [comment] 2014-03-18 08:16
Yeah @kangax but that's not how angular, or any templating engine, for that matter, works.

It's a script tag with standard HTML and some curly braces, which then angular parses and replaces with variables from the controller, instead of javascript. So

```
<script type=text/ng-template id=mytemplate.html>

<h1>{{foo.title}}</h1>
<p>hi {{foo.name}}, how is it going?</p>

</script>
```

becomes

```
<h1>whatever</h1>
<p>hi whoever, how is it going?</p>
```

So this would be ideal https://github.com/kangax/html-minifier/issues/56#issuecomment-37626939 all it would have to do is _not_  ignore script tags if their type matched this option..

**Comment by unbug** [comment] 2014-03-18 09:36
@fxck I think @kangax should take a look at logic-less template engine,might help him to release a new version in a shot time.How those engine works is just warp a bunch of HTML in a script tag.and the type is not "text/javascript",so just mini those scripts as normal HTML tags.

**Comment by fxck** [comment] 2014-03-18 10:10
Yeah right and how does what you said contradicts with what I posted? The only reason I posted an actual example with short description of how it works is because he's apparently unfamiliar with the concept. I never said htmlminifier should do anything with the logic.

Also "is not text/javascript" is kind of stupid, since js will work just fine without any type. Defining what types it should parse(in most cases it will be just one) is definitely more solid solution.

**Comment by unbug** [comment] 2014-03-18 10:15
@fxck Actually I just agreed with your idea,I just though if @kangax  take a look at logic-less template engine might help him to understand your idea :)

**Comment by fxck** [comment] 2014-03-18 10:45
Cool, I think we should perhaps make a new issue, since this one is a) about something else and b) it's already closed..

**Comment by kangax** [comment] 2014-03-18 17:52
@fxck thanks, I didn't understand what you meant by inline javascripts. I'm familiar with the concept and yep, we'll need a new issue for this.

**Comment by fxck** [comment] 2014-03-18 17:58
Done. https://github.com/kangax/html-minifier/issues/139

**Comment by kangax** [comment] 2014-03-21 18:24
I've just added support for minifying JS in on\* attributes (onclick, onmouseover, etc.) and minifying CSS in style attributes.

Would be great if someone could test it out more.

**Comment by XhmikosR** [comment] 2014-03-21 18:25
Seems to work fine @kangax.

BTW, I really think you should disable mangling for the tests only so that they pass. Isn't it possible to pass uglify and clean-css options yet?

**Comment by kangax** [comment] 2014-03-21 19:45
Yeah well, the reason I didn't want to disable mangling is to ensure — via tests — that mangling works. Perhaps it's not that big of a deal.

As far as options — no, haven't added yet. Please do if you have time.
