### ISSUE TITLE
Use lowercase doctype

### ISSUE THREAD

**Issue by ngyikp** [kangax/html-minifier#822] opened 2017-06-03 10:19 UTC
Currently, the `useShortDoctype` option rewrites doctypes to uppercase

HTML5 Boilerplate uses lowercase doctype for several years already, there's not much complaints other than incompatibility with XHTML

https://github.com/h5bp/html5-boilerplate/issues/1522

**Comment by alexlamsl** [comment] 2017-06-03 10:32
Does the current behaviour cause failure in any major browsers?

**Comment by ngyikp** [comment] 2017-06-03 10:33
No

It's just a compression suggestion to shave a few bytes when gzipped

**Comment by alexlamsl** [comment] 2017-06-03 10:36
Unless there is comprehensive proof that nothing breaks and there is a general reduction in gzip sizes across a representative sample, I'm reluctant for any code changes.

**Comment by XhmikosR** [comment] 2018-07-07 20:57
@alexlamsl: you should revisit this. Lowecase `doctype` does save a few bytes and doesn't cause any issues.

**Comment by alexlamsl** [comment] 2018-07-08 05:11
@XhmikosR I shall take your word on compatibility :wink:

Will put together a PR after my belated :birthday: party.

**Comment by XhmikosR** [comment] 2018-07-08 05:13
Hey, it's no my word, it's the community's word ;) You can never beat such extended testing.

**Comment by alexlamsl** [comment] 2018-07-08 09:53
Speaking of community...

https://stackoverflow.com/questions/7020961/uppercase-or-lowercase-doctype

> Note that if you don’t uppercase DOCTYPE in an XHTML document, the XML parser will return a syntax error.

According to the discussions above, if we go for uppercase, everything works - otherwise something might break.

**Comment by XhmikosR** [comment] 2018-07-08 11:28
But when the option to use the **HTML5** doctype is enabled, then that case isn't valid, is it? Or maybe I'm missing something in regards to XHTML since I've never had the need to use such thing.

**Comment by DamonHD** [comment] 2018-07-08 11:33
FWIW I can confirm that in my use case, for minified static (GZIPPed) HTML pages, using "doctype" lowercase does save bytes in the compressed/transferred result.  If I wanted XHTML output then all sorts of other optimisations would have to go away too, such as dropping optional closing tags and element* quoting.

[Edit: * I meant attribute value, sorry!]

**Comment by alexlamsl** [comment] 2018-07-08 11:51
@XhmikosR they mentioned something along the lines of XHTML5

@DamonHD thanks for the observation and the point about optional tags

I was worried about those enterprisy (read: Java) libraries getting upset about conformance issues, but you guys have successfully convinced me otherwise.

Will put that PR together when I get home.

**Closed as completed** 2018-07-08 18:05 UTC
