### ISSUE TITLE
Only remove blank lines...

### ISSUE THREAD

**Issue by ghost** [kangax/html-minifier#129] opened 2014-02-25 16:37 UTC
...rather than put all the tags one after another.

**Comment by kangax** [comment] 2014-02-25 17:30
Can you give an example?

**Comment by ghost** [comment] 2014-02-25 19:34
In addition to this very minified mode:

```
<!DOCTYPE html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><title>Carbon</title><meta name="title" content="Carbon"><meta name="description" content="A front-end framework."><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="viewport" content="width=device-width, initial-scale=1"><link href="stylesheets/application.css" rel="stylesheet"><script defer src="scripts/application.js"></script><link href="images/icn-32x32.png" rel="shortcut icon"><link href="images/icn-152x152.png" rel="apple-touch-icon"></head><body></body></html>
```

This mode. Without empty lines:

```
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Carbon</title>
    <meta name="title" content="Carbon">
    <meta name="description" content="A front-end framework.">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="stylesheets/application.css" rel="stylesheet">
    <script defer src="scripts/application.js"></script>
    <link href="images/icn-32x32.png" rel="shortcut icon">
    <link href="images/icn-152x152.png" rel="apple-touch-icon">
  </head>
  <body></body>
</html>
```

**Comment by kangax** [comment] 2014-02-26 15:57
So spaces are preserved, but newlines are stripped?

Because we already have "collapseWhitespace" option, which when disabled, does this:

``` html
<p>foo</p> <p>bar</p>

<p>baz</p>
```

stays "untouched":

``` html
<p>foo</p> <p>bar</p>

<p>baz</p>
```

**Comment by ghost** [comment] 2014-02-26 19:27
Exactly! Something like `removeEmptyLines: true`.

So this:

```
<p>foo</p> <p>bar</p>

<p>baz</p>
```

Would spit this:

```
<p>foo</p> <p>bar</p>
<p>baz</p>
```

**Comment by LaurentGoderre** [comment] 2014-08-27 17:14
@joelcipriano I opened a PR that does something similar but not quite. It does not preserve whitespace around the line breaks so your output would look like

``` html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Carbon</title>
<meta name="title" content="Carbon">
<meta name="description" content="A front-end framework.">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="stylesheets/application.css" rel="stylesheet">
<script defer src="scripts/application.js"></script>
<link href="images/icn-32x32.png" rel="shortcut icon">
<link href="images/icn-152x152.png" rel="apple-touch-icon">
</head>
<body></body>
</html>
```

**Comment by ghost** [comment] 2014-08-29 12:40
That's great @LaurentGoderre! Thanks!

**Comment by kangax** [comment] 2014-08-29 12:59
Ok, closing as duplicate of #246 and we'll proceed with merging that one in

**Closed as completed by kangax** 2014-08-29 12:59 UTC
Labels: possible-feature
