### ISSUE TITLE
ambiguous double-quotes will make cpu up to 100%

### ISSUE THREAD

**Issue by hwoarangzk** [kangax/html-minifier#385] opened 2015-07-03 12:47 UTC
Even if I escape the ambiguous double-quotes, it will lead to endless loop as well. I expect html-minifier to throw an error when run into this issue. Is there any possibility to update this in the future? The following is the html code:

```
<td><a href="javascript:" class="common-status common-status-<%= status == 2 ? "on" : (status == 3 ? "off" : (status == 1 ? "none" : "")) %>" data-id="<%= id %>"><i><%= status == 2 ? "pass" : (status == 3 ? "fail" : (status == 1 ? "undealt" : "")) %></i><i class="icon icon-pages icon-con-arrow vn"></i></a></td>
```

**Comment by kangax** [comment] 2015-07-03 17:56
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:56 UTC

**Comment by hwoarangzk** [comment] 2015-07-04 10:59
@kangax I don't think this is the duplicate of [#332](https://github.com/kangax/html-minifier/issues/332). Please see the html code with **escaped double-quotes**:

```
<td><a href="javascript:" class="common-status common-status-<%= status == 2 ? \"on\" : (status == 3 ? \"off\" : (status == 1 ? \"none\" : \"\")) %>" data-id="<%= id %>"><i><%= status == 2 ? "pass" : (status == 3 ? "fail" : (status == 1 ? "undealt" : "")) %></i><i class="icon icon-pages icon-con-arrow vn"></i></a></td>
```

If the changed the escaped double-quotes into single-quotes, then html-minifier works fine:

```
<td><a href="javascript:" class="common-status common-status-<%= status == 2 ? 'on' : (status == 3 ? 'off' : (status == 1 ? 'none' : '')) %>" data-id="<%= id %>"><i><%= status == 2 ? "pass" : (status == 3 ? "fail" : (status == 1 ? "undealt" : "")) %></i><i class="icon icon-pages icon-con-arrow vn"></i></a></td>
```

So I don't think the html code with escaped double-quotes is malformed, am I right? And sometimes we have to write escaped double-quotes in our html.

**Comment by kangax** [comment] 2015-07-13 22:50
@hwoarangzk but quotes should be html-escaped (`&quot;`) not slash-escaped

**Comment by hwoarangzk** [comment] 2015-07-16 03:26
@kangax hi, maybe I didn't make it clear. I don't want to display double-quotes in the html so I didn't write `&quot;`. slash-escaped double-quotes can't be used in the html? I think it can be used like the code in my last reply

**Comment by kangax** [comment] 2015-07-21 04:39
> slash-escaped double-quotes can't be used in the html?

No, not that I know of.
