### ISSUE TITLE
Endless loop 100% CPU when parsing invalid HTML

### ISSUE THREAD

**Issue by stefwalter** [kangax/html-minifier#401] opened 2015-09-07 10:16 UTC
I've found a case where html-minifier hangs forever parsing certain invalid HTML. The following string does the trick:

```
<button id="delete-pod-btn" title="delete-pod" class="btn btn-default delete-entity delete-pod pficon pficon-delete" data-toge="modal"  \
              data-target="#adjust-entity" data-entity="{{ selected }}"></button>
```

**Comment by stefwalter** [comment] 2015-09-07 10:16
An example:

```
$ echo '<button id="delete-pod-btn" title="delete-pod" class="btn btn-default delete-entity delete-pod pficon pficon-delete" data-toge="modal"  \
              data-target="#adjust-entity" data-entity="{{ selected }}"></button>' | node_modules/html-minifier/cli.js
```

**Comment by stefwalter** [comment] 2015-09-07 10:17
@sub-mod This is the compilation hang that you ran into. Obviously the HTML is invalid. In your case as a work around, you can just fix the invalid HTML.

**Comment by stefwalter** [comment] 2015-09-07 10:19
Version of html-minifier is:

```
html-minifier@0.7.2 node_modules/html-minifier
```

**Comment by stefwalter** [comment] 2015-09-07 10:21
The hang happens at these lines in the HTML Parser:

```
        if ( chars ) {
          index = html.indexOf('<');

          var text = index < 0 ? html : html.substring( 0, index );
          html = index < 0 ? '' : html.substring( index );

          // next tag
     >     tagMatch = html.match( startTag );
          if (tagMatch) {
            nextTag = tagMatch[1];
          }
          else {
            tagMatch = html.match( endTag );
            if (tagMatch) {
              nextTag = '/' + tagMatch[1];
            }
            else {
              nextTag = '';
            }
          }

          if ( handler.chars ) {
            handler.chars(text, prevTag, nextTag);
          }
```

**Comment by stefwalter** [comment] 2015-09-07 10:21
The startTag regular expression is: `/^<([\w:-]+)((?:\s*[\w:\.-]+(?:\s*(?:(?:=))\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/`

**Comment by sub-mod** [comment] 2015-09-07 11:34
@stefwalter thanks

**Comment by kangax** [comment] 2015-09-07 17:37
Duplicate of https://github.com/kangax/html-minifier/issues/332

**Closed as completed by kangax** 2015-09-07 17:37 UTC
