### ISSUE TITLE
minifier blocks process - 100% cpu usage

### ISSUE THREAD

**Issue by ownagedj** [kangax/html-minifier#443] opened 2015-12-02 09:53 UTC
When I try to minify my file

**test.html**

``` html
<script src="4e650aacd2bf30e34e650aacd2bf30e34e650aacd2bf30e34e650aacd2bf30e3"
```

**commands**

``` bash
node;
var minify = require('html-minifier').minify;
var template = fs.readFileSync('./test.html').toString();
minify(template);
```

The minify process takes like forever. It uses 100% from one of my cpu cores.
The way to stop the process is to kill it with killall node -9

If I use less chars in the src part then it speeds up and results in an `Parse Error` which is correct behavior.

Also tried the other versions (0.8.0, 0.7.0, ...)with the same result

I think there is something broken.

**Comment by GriffinSauce** [comment] 2016-01-06 13:08
I had the same issue with the following snippet of (invalid) HTML:

`<input class="class-name1 class-name2" / data-attributewithoutvalue>`

Sure this is invalid HTML (due to the `/`) but locking the cpu at 100% is not the behaviour I'd expect.
I can't describe the exact cause but can note some exclusions:
- removing the `/` fixes it
- removing the classnames fixes it (produces an error)
- removing the data attribute at the end fixes it

**Comment by duncanbeevers** [comment] 2016-01-06 15:17
This is a duplicate of #332 

The root cause is the html parser being powered by regular expressions which behave well when faced with valid input, but fall victim to catastrophic backtracking when faced with invalid input.

http://www.regular-expressions.info/catastrophic.html

**Closed as completed by duncanbeevers** 2016-01-06 15:17 UTC
