### ISSUE TITLE
Freezing on file

### ISSUE THREAD

**Issue by tivac** [kangax/html-minifier#213] opened 2014-07-29 00:09 UTC
I've got a file that reliably freezes both the NPM version & the online version of html-minifier.

Example CLI usage

```
html-minifier input.micro
```

In the online version I simply hit the "None" shortcut & paste the file. I haven't dug into what is going on yet but was hoping you guys would see something obvious.

**Edit**

Found a smaller repro than I'd originally pasted. This _will_ complete, but it takes a really long time.

``` html
<input data-bind="text" placeholder="<%= i18n("filters.text.label") %>"/>
```

**Original Repro**

``` html
<% var i18n = t.i18nBase("GW2.I18n.newtradingpost"); %>
<input type="text" class="search-text" data-bind="text" placeholder="<%= i18n("filters.text.label") %>"/>
<div class="filterBtn"></div>

<div class="filter-list">
    <% data.filters.forEach(function(filter) { %>
        <div class="search-filter hbox <%= filter.active ?  "active" : "" %>" id="filter<%= filter.section%>">
        <% switch(filter.section) {
            case "level": %>
                <div class="inputs spacer">
                    <label for="levelMin"><%= i18n("filters.level.label") %></label>
                    <div class="hbox">
                        <input type="number" data-bind="level" data-mod="LevelMin" name="levelMin" value="0" max="80" min="0"/>
                        -
                        <input type="number" data-bind="level" data-mod="LevelMax" value="80" max="80" min="0"/>
                        <div class="spacer"></div>
                        <a class="matchMyLevel"><%= i18n("filters.match.level") %></label></a>
                    </div>
                </div>
            <% break; %>
            <% case "available": %>
                <div class="checkbox"></div>
                <div class="inputs">
                    <input name="available" type="checkbox" data-bind="available"/>
                    <label for="available"><%= i18n("filters.available.label") %></label>
                </div>
            <% break; %>
            <% case "rarity": %>
                <div class="inputs">
                    <div class="selectbox" data-bind="rarity"><%= i18n("filters.rarity.all") %></div>
                    <div class="selectmenu">
                        <div data-value=""><%= i18n("filters.rarity.all") %></div>
                        <% Object.keys(filter.query.Rarity.enums).forEach(function(rarity) { %>
                            <div data-value="<%= rarity %>"><%= i18n("filters.rarity." + rarity) %></div>
                        <% }); %>
                    </div>
                </div>
            <% break; %>
            <% case "combatstats": %>
                <div class="inputs">
                    <div class="hbox">
                        <div>
                            <div class="selectbox" data-targeted="combatstat"><%= i18n("filters.combatstats.label") %></div>
                            <div class="selectmenu">
                                <div data-value=""><%= i18n("filters.combatstats.label") %></div>
                                <% filter.query.select.forEach(function(combat) { %>
                                    <div data-value="<%= combat %>"><%= i18n("filters." + combat + ".label") %></div>
                                <% }); %>
                            </div>
                        </div>
                        <input type="number" class="combatstat" data-target="combatstat" data-bind="combatstat" data-mod="min" name="combatStatMin" value="1"/>
                    </div>
                </div>
            <% break; %>
            <% case "power": %>
            <% case "precision": %>
            <% case "toughness": %>
            <% case "vitality": %>
            <% case "criticaldamage": %>
            <% case "healing": %>
            <% case "conditiondamage": %>
            <% case "agonyresistance": %>
                <div class="inputs spacer">
                    <label for="<%= filter.section %>Min"><%= i18n("filters." + filter.section + ".label") %></label>
                    <div class="hbox">
                        <input type="number" data-bind="<%= filter.section %>.min" name="<%= filter.section %>Min"/>
                        -
                        <input type="number" data-bind="<%= filter.section %>.max"/>
                    </div>
                </div>
            <% break; %>
        <% } %>
        </div>
    <% }); %>
    <button class="button resetFilters"><%= i18n("filters.reset") %></button>
</div>
```

**Comment by tivac** [comment] 2014-07-29 00:17
Managed to actually get an error for the smaller repro by using it via a node script.

```
...html-minifier\dist\htmlminifier.js:293
        throw 'Parse Error: ' + html;
                              ^
Parse Error: <input data-bind="text" placeholder="<%= i18n("filters.text.label") %>"/>
```

**Comment by tivac** [comment] 2014-07-29 17:13
Here's the likely issue.

http://regexr.com/3980m

The regex being used to parse tags (`/^<([\w:-]+)((?:\s*[\w:-]+(?:\s*(?:(?:=))\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)/>`) times out trying to process `<input data-bind="text" placeholder="<%= i18n("filters.text.label") %>"/>` on regexr. I see a similar huge delay when stepping through via node-inspector. I haven't taken the time to grok the regex to see where the likely error is, but this seems like a scary one to fix.

In code terms it's freezing on the following line:

https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlparser.js#L227

**Comment by kangax** [comment] 2014-07-29 17:15
Thanks, Pat! We'll look into it.

/cc @duncanbeevers

**Comment by duncanbeevers** [comment] 2014-07-29 17:18
Hey @tivac 
The issue here is that you've got ambiguous double-quotes.

``` html
<input data-bind="text" placeholder="<%= i18n("filters.text.label") %>"/>
```

Should be

``` html
<input data-bind="text" placeholder="<%= i18n('filters.text.label') %>"/>
```

I wrote a small entry discussing this type of parsing error, and hope to publish it shortly.
https://gist.github.com/duncanbeevers/39635525529e72ecd145

**Comment by tivac** [comment] 2014-07-29 18:41
@duncanbeevers Interesting, I guess I expected it to do more aggressive ignoring of content within `<% ... %>`.

I made that change & html-minifier still doesn't like that file, but I think having to change our quoting standard in this one case is probably a deal-breaker anyways. Thanks for the answer!

**Comment by duncanbeevers** [comment] 2014-07-29 19:53
This situation shouldn't cause the minification process to hang, but should instead let the user know what's going on. Should be addressed by #192 , Better Parsing Errors.

**Comment by duncanbeevers** [comment] 2014-08-21 01:29
I think there are a number of places where we're using greedy regular expressions where non-greedy would do, and my intuition is that making this switch could significantly reduce both RAM usage and overall run-time.

**Comment by dhoko** [comment] 2015-06-29 14:25
Another ex to freeze both the NPM version & the online version of html-minifier.

``` html
<input
  type="number"
  class="commandCheckout-input-cvc"
  name="cvc"
  placeholder"(123)">
```

It seems there is an infinite loop.

**Comment by kangax** [comment] 2015-07-03 17:54
Duplicate of #332

**Closed as completed by kangax** 2015-07-03 17:54 UTC
Labels: bug
