### ISSUE TITLE
Minifier silently changes order of elements

### ISSUE THREAD

**Issue by YuliaTsareva** [kangax/html-minifier#578] opened 2016-03-21 23:24 UTC
Since version 1.3.0 html-minifier silently changes order of elements if inline elements contain block elements.
E.g., `<span><div>Hello</div></span>` after minification looks like `<span></span><div>Hello</div>`.

I understand that such code is not valid in HTML5. But the browsers render it and there are projects with such peaces of code.

Some popular dev utils depend on html-minifier and now them generate wrong minified code (e.g., gulp-htmlmin and webpack html-loader).

I suppose such code manipulation is undesirable for minifier. Or at least it should be published as major update to not break existing projects.

**Comment by kangax** [comment] 2016-03-22 00:14
I'll be on a plane for the next few hours but I'll try to push a new release (with the fix) to npm.

**Comment by alexlamsl** [comment] 2016-03-22 03:26
Duplicate of #557

@kangax changelog is ready at #576 - have a nice trip :wink:

**Closed as completed by alexlamsl** 2016-03-22 03:26 UTC
