### ISSUE TITLE
html-minifier produces invalid inline SVG

### ISSUE THREAD

**Issue by alefteris** [kangax/html-minifier#45] opened 2013-04-11 16:58 UTC
This is the original SVG in my HTML:

``` html
<body>
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
    <rect width="20" height="3" y="2" fill="#fff"/>
    <rect width="20" height="3" y="8.5" fill="#fff"/>
    <rect width="20" height="3" y="15" fill="#fff"/>
</svg>
</body>
```

And here is the result after html-minifier:

``` html
<body>
<svg xmlns="http://www.w3.org/2000/svg" width=20 height=20>
    <rect width=20 height=3 y=2 fill="#fff">
    <rect width=20 height=3 y=8.5 fill="#fff">
    <rect width=20 height=3 y=15 fill="#fff">
</svg>
```

The SVG will not display properly any more (only the first rect is displayed). If I add ending slashes in the rect elements, it will display property, but it's still not valid SVG.

So maybe html-minifier shouldn't touch SVGs?

I originally reported it against gruntjs/grunt-contrib-htmlmin#19, that uses html-minifier.

**Comment by matt-bailey** [comment] 2013-04-15 17:30
I'm not sure if this is a related issue, but using object tags seems to create a similar problem (I'm also using [grunt-htmlmin](https://github.com/gruntjs/grunt-contrib-htmlmin), which uses html-minifier). However, I'm a complete Grunt noob, so it may well be something I'm doing wrong...

This is my source html:

``` html
<object type="image/svg+xml" data="image.svg">
    <div>[fallback image]</div>
</object>
```

This is the output html:

``` html
<object type="image/svg+xml" data="image.svg">
    </object><div>[fallback image]</div>
```

As you can see, the inner div is somehow magically moved outside of the object.

All the html-minifier options are set to whatever the defaults are.

**Comment by kangax** [comment] 2013-06-19 11:10
This could possibly be integrated with https://github.com/svg/svgo

**Comment by onearmfrog** [comment] 2013-10-02 09:26
Bug still persists, tags inside svg are broken. I could not find any option to disable html-min for specific tags to solve this.

**Comment by xdhmoore** [comment] 2013-12-06 18:03
I am having the same issue with inline svg in my html.  I have a couple <g> tags whose contents are populated with d3.js:

```
<svg>
  <g class="stuff"/>
  <g class="otherstuff"/>
</svg
```

htmlmin produces the following:

```
<svg>
  <g class="stuff">
  <g class="otherstuff">
</svg>
```

Which causes the browser to interpret it as:

```
<svg>
  <g class="stuff">
    <g class="otherstuff"></g>
  </g>
</svg>
```

**Comment by kangax** [comment] 2014-02-03 20:40
Duplicate of #76

**Closed as completed by kangax** 2014-02-03 20:40 UTC
Labels: possible-feature
