### ISSUE TITLE
Elements incorrect output

### ISSUE THREAD

**Issue by softsimon** [kangax/html-minifier#577] opened 2016-03-21 22:02 UTC
After upgrading to the latest version, elements got misplaced in my project.

I can use the example code to reproduce this:

```
var result = minify('<h1><my-component></my-component></h1>', {
  removeAttributeQuotes: true
});
```

Results in:

`<h1></h1><my-component></my-component>`

My component escapes the h1-tag.

**Comment by alexlamsl** [comment] 2016-03-21 22:14
Duplicate of #557

**Closed as completed by alexlamsl** 2016-03-21 22:14 UTC
