### ISSUE TITLE
Premature Closing Tag

### ISSUE THREAD

**Issue by willpracht** [kangax/html-minifier#560] opened 2016-03-17 17:18 UTC
An issue we've run into recently with an upgrade from `v1.2.0` to `v1.3.0`:

This template:

``` html
<span><my-angular-directive></my-angular-directive></span>
```

...becomes...

``` html
<span></span><my-angular-directive></my-angular-directive></span>
```

I'm wondering if this has something to do with the regex changes between `v1.2.0` and `v1.3.0`.

**Comment by alexlamsl** [comment] 2016-03-17 17:27
Duplicate of #557 - please follow that issue.

**Closed as completed by alexlamsl** 2016-03-17 17:27 UTC

**Comment by willpracht** [comment] 2016-03-17 23:19
Ah, my bad :). Thanks!
