### ISSUE TITLE
Remove classes

### ISSUE THREAD

**Issue by ilovebeatles** [kangax/html-minifier#619] opened 2016-04-12 15:29 UTC
Hello, you doing a great job with that task. Is there a way to delete all css classes from minify html?

**Comment by alexlamsl** [comment] 2016-04-12 15:47
Can you elaborate on what you mean?

**Comment by ilovebeatles** [comment] 2016-04-13 10:42
Sure. Something like this:
<div class="foo">bar</div> => <div>bar</div>

**Comment by ilovebeatles** [comment] 2016-04-13 10:44
Sure. Something like this:

`<div class="foo">bar</div> => minify => <div>bar</div>`

**Comment by alexlamsl** [comment] 2016-04-13 12:32
In that case it's a duplicate of #322 then. Please follow that issue.

**Closed as completed by alexlamsl** 2016-04-13 12:32 UTC
